name = "Tiny World Preset"
description = ""
author = "ChubbyBunny"
version = "1.2"
api_version = 10
dst_compatible = true
dont_starve_compatible = false
reign_of_giants_compatible = false
shipwrecked_compatible = false
client_only_mod = false
all_clients_require_mod = true
server_only_mod = false
icon_atlas = "modicon.xml"
icon = "modicon.tex"